### ISSUE TITLE
Not really an issue, but a small thought/suggestion

### ISSUE THREAD

**Issue by RetroNutcase** [CrazyAmphibian/stagebasedprogression#1]
How hard would it be to turn this into an Artifact? That way you could choose when you do and don't want to use it per gameplay session instead of having to quit out of the game to enable/disable the mod each time.

Heck, I even thought of a halfway decent name: Artifact of Escalation

**Comment by CrazyAmphibian** [comment]
I don't know how to make artifacts, and C# is kicking my ass.
That would require more dependencies so it'd be more appropriate to make a new mod in my opinion.
